home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', view=views.index, name='index'),
    
]

orders_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("clients/", include("clients.urls")),
    path("products/", include("products.urls")),
    path('vendors/', include('vendors.urls'))
]

vendors/urls.py
from django.urls import path

from vendors import views

app_name = 'vendors'

urlpatterns = [
    path('', view=views.vendors,name='vendor-list'),
    path('add',view=views.create_vendor,name='vendor-add'),
]

vendors/models.py
from django.db import models

# Create your models here.
class Vendor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    document = models.IntegerField()
    phone = models.IntegerField()
    address = models.CharField(max_length=50)
    email = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.id} | {self.document} | {self.name}'


vendors/forms.py
from django import forms

class VendorForm(forms.Form):
    name = forms.CharField(
        label="Nombre",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "vendor-name",
                "placeholder": "Nombre Vendedor",
                "required": "True",
            }
        ),
    )
    document = forms.IntegerField(
        label="Documento",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "vendor-document",
                "placeholder": "Documento Vendedor",
                "required": "True",
            }
        ),
    )
    phone = forms.IntegerField(
        label="Teléfono",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "vendor-phone",
                "placeholder": "Teléfono Vendedor",
                "required": "True",
            }
        ),
    )
    address = forms.CharField(
        label="Dirección",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "vendor-address",
                "placeholder": "Dirección Vendedor",
                "required": "True",
            }
        ),
    )
    email = forms.CharField(
        label="Correo Electrónico",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "vendor-email",
                "placeholder": "Correo electrónico Vendedor",
                "required": "True",
            }
        ),
    )

vendors/views.py
from django.shortcuts import render
from django.contrib import messages

from vendors.models import Vendor
from vendors.forms import VendorForm

# Create your views here.


def create_vendor(request):
    if request.method == 'POST':
        vendor_form = VendorForm(request.POST)
        if vendor_form.is_valid():
            data = vendor_form.cleaned_data
            actual_objects = Vendor.objects.filter(
                name=data['name'], document=data['document']).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request, f"Vendedor {data['name']} - {data['document']} ya existe",)
            else:
                vendor = Vendor(name=data['name'], document=data['document'],
                                phone=data['phone'], email=data['email'], address=data['address'],)
                vendor.save()
                messages.success(
                    request, f"Vendedor {data['name']} - data={data['document']} creado con exito!",)

            return render(request=request, context={'vendors': Vendor.objects.all()}, template_name="vendor_list.html")

    return render(request, 'vendor_form.html', {
        'form': VendorForm
    })


def vendors(request):
    vendors = Vendor.objects.all()
    return render(request, "vendor_list.html", {'vendors': vendors})

vendors/templates/vendor_form.html
{% extends "home/index.html" %}

{% load static %}

{% block orders_manager_content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Nuevo Vendedor</h1>
</div>
<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" class="btn btn-primary" value="Guardar" />
        <a href="{% url 'vendors:vendor-list' %}" class="btn btn-danger">Cancelar</a>
    </form>
    
</div>
<hr/>
{% endblock %}

vendors/templates/vendor_list.html
{% extends "home/index.html" %}

{% load static %}

{% block orders_manager_content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Vendedores</h1>
    <a href="{% url 'vendors:vendor-add' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
        class="fas fa-user-plus fa-sm text-white-50"></i>Nuevo Vendedor</a>
</div>
 <div class="row">
    {% for vendor in vendors %}
    <div class="card col-lg-5 m-2">
        <div class="card card-title">
            <h2> {{vendor.name}}</h2>
            <h3> {{vendor.document}}</h3>
        </div>
        <div class="card-body">
            <h4> Corre Electronico: {{vendor.email}}</h4>
            <h4> Telefono: {{vendor.phone}}</h4>
            <h4> Direccion: {{vendor.address}}</h4>
        </div>
    </div>
    <br>
{% endfor %}
 </div>
{% endblock %}