clients/urls.py
from django.urls import path

from clients import views

app_name = 'clients'
urlpatterns = [
    path('', view=views.clients, name='client-list'),
    path('add', view=views.create_client, name='client-add'),
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', view=views.index, name='index'),
    
]

orders_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("clients/", include("clients.urls")),
    path("products/", include("products.urls")),
    path('vendors/', include('vendors.urls'))
]

clients/models.py
from django.db import models

# Create your models here.

class Client(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    nit = models.IntegerField()
    address = models.CharField(max_length=40)
    phone = models.IntegerField()
    email = models.CharField(max_length=40)

    def __str__(self):
        return str(self.id) + ' - ' + str(self.nit) + ' - ' + self.name

clients/forms.py
from django import forms

class ClientForm(forms.Form):
    name = forms.CharField(
        label="Nombre:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "client-name",
                "placeholder": "Nombre del cliente",
                "required": "True",
            }
        ),
    )

    nit = forms.IntegerField(
        label="Nit:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "client-nit",
                "placeholder": "NIT del cliente",
                "required": "True",
            }
        ),
    )

    email = forms.CharField(
        label="Correo Electrónico:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "client-email",
                "placeholder": "Correo electrónico del cliente",
                "required": "True",
            }
        ),
    )

    address = forms.CharField(
        label="Dirección:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "client-address",
                "placeholder": "Dirección del cliente",
                "required": "True",
            }
        ),
    )

    phone = forms.IntegerField(
        label="Telefono:",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "client-phone",
                "placeholder": "Telefono del cliente",
                "required": "True",
            }
        ),
    )

clients/views.py
from django.contrib import messages
from django.shortcuts import render

from clients.models import Client
from clients.forms import ClientForm

def clients(request):
    clients = Client.objects.all()
    context_dict = {"clients": clients}
    return render(
        request, 'client_list.html',
        context_dict,

    )


def create_client(request):
    if request.method == "POST":
        client_form = ClientForm(request.POST)
        if client_form.is_valid():
            data = client_form.cleaned_data
            actual_objects = Client.objects.filter(
                name=data["name"], nit=data["nit"]
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El cliente {data['name']} - {data['nit']} ya existe",
                )
            else:
                client = Client(name=data["name"], nit=data["nit"],phone=data['phone'], email=data['email'], address=data['address'],)
                client.save()
                messages.success(
                    request,
                    f"cliente {data['name']} - {data['nit']} creado exitosamente!",
                )

            clients = Client.objects.all()
            context_dict = {"clients": clients}
            return render(
                request, 'client_list.html',
                context_dict,)

    return render(request, 'client_form.html', {
        'form': ClientForm
    })

clients/templates/client_form.html
{% extends "home/index.html" %}
{% load static %}


{% block orders_manager_content %}

<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Guardar cliente" />
    </form>
</div>

<!-- Divider-->
<hr/>

{%  endblock %}

clients/templates/client_list.html
{% extends "home/index.html" %}
{% load static %}


{% block orders_manager_content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Clientes</h1>
    <a href="{% url 'clients:client-add' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
        class="fas fa-download fa-sm text-white-50"></i> Nuevo cliente </a>
</div>

<div class="col-lg6 mb-4">
</div>

{% for client in clients %}
    <!-- Post preview-->
    <div class="card-body">
        <h2>El nombre del cliente  {{ client.name }}</h2>
        <h3>Nit: {{ client.nit }}</h3>
    </div>
    <!-- Divider-->
    <hr/>
{% endfor %}

{% endblock %}